### ISSUE TITLE
Rename repo to RSE-leaders.github.io

### ISSUE THREAD

**Issue by sdruskat** [RSE-leaders/researchsoftware.org#13]
In order to be able to run sub-sites from different repos, we'd need to rename this repository to `RSE-leaders.github.io`. Once this is done, the [SORSE20](https://github.com/RSE-leaders/SORSE20) and potentially an Intl. RSE Leaders Meeting 2020 page could be developed separately in their respective repositories.

Then, their "original" GH Pages URLS (e.g., `RSE-leaders.github.io/SORSE20`) would be caught by the custom domain name and rendered as `researchsoftware.org/SORSE20`.

I'd be happy to make the move, unless it would break the current setup (perhaps @shensicle or @benvanwerkhoven know?).

**Comment by sdruskat** [comment]
FWIW, we have the same setup for https://github.com/DE-RSE/de-rse.github.io & https://github.com/DE-RSE/deRSE20.

**Comment by Chilipp** [comment]
see also https://github.com/RSE-leaders/SORSE20/issues/56#issuecomment-642839535. I already contacted @alysbrett, @ClaireWyatt and @jag1g13 on slack. So no clue about the correct channel to discuss this :sweat_smile:

**Comment by alysbrett** [comment]
My two reservations were that I don't know if it would break anything, and that this website is not really "the website" of this Github org (the org is (or was originally) the UK RSE leaders group and the website is an international RSE movement landing page, not just about RSE leaders). The correct answer is probably to either make a new org that is called RSE international or similar and make this the website of that org, or to have this website all in one repo within this org, but either of those would probably involve delay so if we can establish it won't break something I guess it would be OK to rename it.

**Comment by Chilipp** [comment]
the only thing that might get broken, would be if you have a repository here already, say https://github.com/RSE-leaders/my-awesome-repository, that is currently hosted via Github pages under https://rse-leaders.github.io/my-awesome-repository. 

After renaming https://github.com/RSE-leaders/researchsoftware.org to https://github.com/RSE-leaders/rse-leaders.github.io, `my-awesome-repository` would be hosted under https://researchsoftware.org/my-awesome-repository (although https://rse-leaders.github.io/my-awesome-repository would automatically forward to the new URL). 

But as this is not the case anyway, I don't think it can break anything @alysbrett.

**Comment by jag1g13** [comment]
Alternatively, either this organisation could be renamed - if its primary purpose is actually to host this web page; or this web page could be moved to a new organisation, along with the SORSE repo - if the primary purpose of this organisation is actually to host UK RSE Leaders content

**Comment by Chilipp** [comment]
I am happy with both solutions. Who does have the authority to decide it?

**Comment by jag1g13** [comment]
There's an RSE Leaders meeting this week, on the 19th so we could ask them to suggest a preferred option.  Otherwise, I believe Alys has authority

**Comment by Chilipp** [comment]
Yes, it would be great if you could make a decision with the leaders there  @jag1g13!

**Comment by Chilipp** [comment]
@jag1g13 and @alysbrett: Any updates on this?

**Comment by Chilipp** [comment]
closing this as we moved to https://github.com/SORSE
