### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by Chilipp** [RSE-leaders/researchsoftware.org#16]
@RSE-leaders/researchsoftware-org For some reason, https://researchsoftware.org cannot be accessed since a couple of hours. Any idea, why?

**Comment by benvanwerkhoven** [comment]
I have no idea. I just did a whois lookup, it seems Canarie is still the owner of the domain, it's not like it has expired. It seems canarie.ca is down entirely. So I would guess it's a temporary issue with Canarie's webservers or something.

**Comment by benvanwerkhoven** [comment]
It seems the issue at Canarie has been resolved and the website is back up.

**Comment by Chilipp** [comment]
Great, thanks for checking @benvanwerkhoven :smiley:
