### ISSUE TITLE
researchsoftware.org listed as blocked domain

### ISSUE THREAD

**Issue by sdruskat** [RSE-leaders/researchsoftware.org#20]
To whom it may concern (@benvanwerkhoven maybe?) :

I have recently sent an email to Arizona State Uni which was blocked. I've now heard back from ASU why that was:

> Our Server folks took a look at the logs, and it looks like your emails are being blocked due to a bad link, the URL researchsoftware DOT org. This can be verified at the following link. https://www.barracudacentral.org/lookups/lookup-reputation. You'll either need to remove the URL, or if you own the domain, please reach out to barracuda to have them improve reputation.

I've checked, and Barracuda says:

> The domain name researchsoftware.org is listed on Barracuda's Intent Block List. To report any issues regarding your domain reputation, please contact intent@barracuda.com.
The domain name researchsoftware.org was found under the following categories: search-engines-portals

**Comment by sdruskat** [comment]
Seems that whoever is responsible for the domain at CANARIE would be the right person to follow this up.

**Comment by benvanwerkhoven** [comment]
I've never heard of barracuda before and I don't know what they have against our website, nor what they mean with "search-engines-portals". The domain is indeed owned by CANARIE, so perhaps @shensicle can help out.

**Comment by benvanwerkhoven** [comment]
I've contacted intent@barracuda.com. Let's hope we get a response.

**Comment by benvanwerkhoven** [comment]
I've received a reply, our domain will be removed from the list!

**Comment by sdruskat** [comment]
Great, thanks Ben!
