### ISSUE TITLE
how to get edit access

### ISSUE THREAD

**Issue by martinhorsch** [RSE-leaders/researchsoftware.org#22]
do we need to be accepted into a project or group, or is being registered on github enough?

**Comment by sdruskat** [comment]
Hi @martinhorsch, for the time being, please suggest changes via fork & pull request. We're still in the process of setting up governance for this repository, and hence cannot make decisions about adding direct contributors at the moment. 

If you need any pointers towards documentation how to fork and create a pull request, please feel free to re-open this issue and let me know.

Thanks!
