### ISSUE TITLE
License

### ISSUE THREAD

**Issue by benvanwerkhoven** [RSE-leaders/researchsoftware.org#23]
Alejandra Gonzalez-Beltran asked if the blogposts on the website have a license, when I checked I noticed that the website doesn't have a license at all. I'd like to change that ASAP, and I think we should probably use a CC-BY license, what do you think? @sdruskat

**Comment by sdruskat** [comment]
Thanks, important point. I'd agree with using CC-BY Intl 4.0 as default (but allow others (less restrictive) if requested by authors), and will try to ask all contributors of blog posts if they'd be okay with that.

Should also include this in the footer.

**Comment by benvanwerkhoven** [comment]
yeah good points, I fully agree!

**Comment by sdruskat** [comment]
Emails sent, and first answers coming in.

Tracking:

### How to set up intl RSE assoc
  - [ ] James Hetherington
  - [ ] Ben van Werkhoven
  - [ ] Rob Haines
  - [ ] Stephan Janosch
  - [ ] Paul Hagan
  - [ ] Samar Elsheikh
  - [ ] Radek Lonka
  - [ ] License attached to post

### Intl RSE Leaders Workshop
  - [x] Alys
  - [ ] License attached to post

### Tools for managing RSE projects
  - [ ] Mark Woodbridge
  - [ ] James Meakin
  - [ ] Jim Procter
  - [ ] Jeffrey Salmond
  - [ ] Daniel Smith
  - [ ] License attached to post

### 2nd Workshop summary
  - [x] Stephan Druskat
  - [ ] Radovan Bast
  - [ ] Ian Cosden
  - [ ] Anne Fouilloux
  - [ ] Simon Hettrick
  - [ ] Dan Katz
  - [ ] Johan Philips
  - [ ] Peter van Heusden
  - [ ] Ben van Werkhoven
  - [ ] Claire Wyatt
  - [ ] License attached to post

### Research Software Engineer's Toolkit
  - [ ] Jeremy Cohen (asked for group)
  - [ ] License attached to post

### Single Entry Point & Marketplace
  - [ ] Julia Damerow (asked for group)
  - [ ] License attached to post

### How do RSE groups work?
  - [ ] Will Usher (asked for group)
  - [ ] License attached to post

**Comment by agbeltran** [comment]
+1 to CC-BY Intl 4.0 by default - thanks for looking into this

**Comment by StephanJanosch** [comment]
+1 for suggested License

**Comment by sdruskat** [comment]
(An author just let me know that the posts were originally published under CC-BY on the UK RSE site, but when moving them, the badge/notice may have been lost.)

**Comment by sdruskat** [comment]
Approval collected from authors & transferred (https://github.com/RSE-leaders/researchsoftware.org/issues/23#issuecomment-730958565), so I've now set up a footer & added a license file to the repo, and am closing this.
