### ISSUE TITLE
Decide on CoC and add links where necessary

### ISSUE THREAD

**Issue by sdruskat** [RSE-leaders/researchsoftware.org#27]
During the Council Meeting on 1 April, we should decide on a CoC to use for the Council and the website, then add links where it's necessary:

- [x] CONTRIBUTING.md
- [x] Website
- [x] ...

**Comment by benvanwerkhoven** [comment]
Since the council has decided on a CoC and the contributing guidelines have been merged, I think this issue can be closed? Or am I missing something?

**Comment by sdruskat** [comment]
Yes, all done, closing.
