### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by sdruskat** [RSE-leaders/researchsoftware.org#57]
GitHub will create new repositories with `main` as default branch.

As changing the name isn't costly (the only manual change is in existing local environments) but allows us to move away from controversial terminology, I'm all for making this change.

Should be briefly discussed at the next meeting of the Council.

**Comment by danielskatz** [comment]
This is becoming a standard practice, and I'm not even sure we need to discuss it

**Comment by sdruskat** [comment]
Okay, I'll just do it then.

**Comment by sdruskat** [comment]
Done.

**Comment by sdruskat** [comment]
Reopening as renaming `master` to `main` may have broken deployment for some reason...

**Comment by sdruskat** [comment]
Re-renamed and re-re-renamed, and now deployment seems to work again.
